version: '3'

services:
  pusher:
    environment:
      - PORT=8585
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8585:8585
    depends_on:
      - redis

  redis:
    image: redis:3.2
    ports:
      - 6379:6379
